import type { MDXComponents } from "mdx/types";
import {
  Blockquote,
  Code,
  BlogPostTitle,
  H2,
  H3,
  H4,
  H5,
  H6,
  HorizontalRule,
  MdxImage,
  Link,
  OrderedList,
  Paragraph,
  Pre,
  TD,
  TH,
  Table,
  UnorderedList,
} from "./src/components/ui/typography";

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    ...components,
    p: Paragraph,
    img: MdxImage,
    blockquote: Blockquote,
    hr: HorizontalRule,
    ol: OrderedList,
    ul: UnorderedList,
    code: Code,
    pre: Pre,
    a: Link,
    h1: BlogPostTitle,
    h2: H2,
    h3: H3,
    h4: H4,
    h5: H5,
    h6: H6,
    table: Table,
    td: TD,
    th: TH,
  };
}
